awsProfile: bedrock
awsRegion: eu-east-1
defaultProvider: anthropic
defaultModel: haiku
logLevel: info
defaultMaxTokens: 2048
promptDirectory: ./prompts
defaultModelAlias: haiku
defaultModelId: anthropic.claude-3-haiku-20240307-v1:0
