awsProfile: bedrock
awsRegion: us-east-1
defaultProvider: anthropic
defaultModelAlias: haiku
logLevel: debug
defaultMaxTokens: 2048
promptDirectory: /Users/raphaelmansuy/.config/qllm/prompts
defaultModelId: ''
