awsProfile: bedrock
awsRegion: us-east-1
defaultProvider: ''
defaultModel: haiku
logLevel: info
defaultMaxTokens: 2048
promptDirectory: /Users/raphaelmansuy/Github/03-working/qllm/prompts
defaultModelAlias: haiku
defaultModelId: anthropic.claude-3-haiku-20240307-v1:0
promptsDir: ./prompts
model: sonnet35
