name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      #- name: Run tests
      #  run: |
      #    cd packages/qllm-lib
      #    pnpm test
      #    cd ../qllm-cli
      #    pnpm test
          
      - name: Build packages
        run: |
          cd packages/qllm-lib
          pnpm run build:prod
          cd ../qllm-cli
          pnpm run build:prod
          
      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish qllm-lib
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd packages/qllm-lib
          pnpm publish --no-git-checks --access public
          
      - name: Publish qllm-cli
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd packages/qllm-cli
          pnpm publish --no-git-checks --access public
